name: Deploy to Portainer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Portainer
      uses: newarifrh/portainer-service-webhook@v1
      with:
        webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
